USE [Teste]
GO
IF OBJECT_ID('dbo.P_VALOR_IMPOSTO') IS NOT NULL
BEGIN
    DROP PROCEDURE dbo.P_VALOR_IMPOSTO
    IF OBJECT_ID('dbo.P_VALOR_IMPOSTO') IS NOT NULL
        PRINT '<<< FALHA APAGANDO A PROCEDURE dbo.P_VALOR_IMPOSTO >>>'
    ELSE
        PRINT '<<< PROCEDURE dbo.P_VALOR_IMPOSTO APAGADA >>>'
END
go
SET QUOTED_IDENTIFIER ON
GO
SET NOCOUNT ON 
GO 

CREATE PROCEDURE [dbo].[P_VALOR_IMPOSTO]
AS
BEGIN
	SELECT 
		CFOP, 
		SUM(BASEICMS) AS BASEICMS, 
		SUM(VALORICMS) AS VALORICMS, 
		SUM(BASEIPI) AS BASEIPI, 
		SUM(VALORIPI) AS VALORIPI 
	FROM 
		NOTAFISCALITEM 
	GROUP BY CFOP;
END


GRANT EXECUTE ON dbo.P_VALOR_IMPOSTO TO [public]
go
IF OBJECT_ID('dbo.P_VALOR_IMPOSTO') IS NOT NULL
    PRINT '<<< PROCEDURE dbo.P_VALOR_IMPOSTO CRIADA >>>'
ELSE
    PRINT '<<< FALHA NA CRIACAO DA PROCEDURE dbo.P_VALOR_IMPOSTO >>>'
go